name: generate github pages

on:
  push:
    branches:
      - master

jobs:
  generate-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: DeployRemote
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DST_DEPLOY_KEY }}
          external_repository: marinarudnitskaya/blog-public
          publish_branch: v1
          publish_dir: ./public
